# Generated by Django 4.0.4 on 2022-10-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated_at',
        ),
    ]
