# Generated by Django 4.0.4 on 2022-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inv',
            field=models.TextField(default='empty'),
        ),
    ]
