# Generated by Django 4.0.4 on 2022-11-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mani',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
