# Generated by Django 4.0.4 on 2023-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.ImageField(default=0, upload_to=None),
        ),
    ]
