# Generated by Django 4.0.4 on 2023-01-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='field_name',
            new_name='picture',
        ),
    ]
