# Generated by Django 4.0.4 on 2023-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inv',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mani',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to=None),
        ),
    ]
