# Generated by Django 4.2 on 2023-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_product_picture_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(max_length=100),
        ),
    ]
